# Site settings
title: Gemma Baugh
email: gemma.a.baugh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Gemma Baugh is happy you have visited her website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gemmabaugh.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  gemmabaugh

# Build settings
markdown: kramdown
